# Generated by Django 6.0.1 on 2026-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local FAISS Indexing'), ('google', 'Google File Search'), ('rag', 'RAG')], default='local', help_text='Type of storage backend (local FAISS or Google File Search)', max_length=20),
        ),
    ]
