# Generated by Django 6.0.1 on 2026-01-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(help_text="Unique project identifier (e.g., 'local_20250120_143000_my_project')", max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Human-friendly name for the project', max_length=255)),
                ('storage_type', models.CharField(choices=[('local', 'Local FAISS Indexing'), ('google', 'Google File Search')], default='local', help_text='Type of storage backend (local FAISS or Google File Search)', max_length=20)),
                ('external_store_id', models.CharField(blank=True, help_text='ID from external service (e.g., Google Store ID)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the project')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is active')),
                ('document_count', models.IntegerField(default=0, help_text='Number of documents in this project')),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='When documents were last indexed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['storage_type', 'is_active'], name='projects_pr_storage_acbf1b_idx'), models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='The system prompt content for this project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project this prompt is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='system_prompt', to='projects.project')),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompts',
            },
        ),
    ]
