# Generated by Django 6.0.1 on 2026-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chunking',
            field=models.CharField(choices=[('fixed-size', 'Fixed-size'), ('sentence-paragraph', 'Sentence/paragraph'), ('recursive', 'Recursive'), ('document-structure', 'Document-structure'), ('semantic', 'Semantic')], default='fixed-size', help_text='Text chunking strategy', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_prompt',
            field=models.BooleanField(default=False, help_text='Whether to use a custom prompt'),
        ),
        migrations.AddField(
            model_name='project',
            name='document_parsing',
            field=models.CharField(choices=[('pymupdf', 'PyMUPDF'), ('markitdown', 'markitdown')], default='pymupdf', help_text='Document parsing backend', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='embedding_model',
            field=models.CharField(choices=[('gemini-1', 'Gemini embedding 1'), ('google-2', 'Google embedding 2'), ('gemma', 'fkEmbeddingGemma')], default='gemini-1', help_text='Embedding model to use', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='synthesizer',
            field=models.BooleanField(default=False, help_text='Enable or disable the synthesizer'),
        ),
    ]
