# Generated by Django 6.0.1 on 2026-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_chunking_project_custom_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_markitdown',
            field=models.BooleanField(default=False, help_text='Use MarkItDown pipeline'),
        ),
        migrations.AddField(
            model_name='project',
            name='use_structural_grading',
            field=models.BooleanField(default=False, help_text='Use structural quality grading'),
        ),
    ]
