# Generated by Django 6.0.1 on 2026-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document_parsing',
            field=models.CharField(choices=[('pymupdf', 'PyMUPDF'), ('markitdown', 'markitdown')], default='markitdown', help_text='Document parsing backend', max_length=50),
        ),
    ]
