# Generated by Django 6.0.1 on 2026-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_document_parsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google File Search'), ('postgres', 'Postgres RAG')], default='local', help_text='Type of storage backend (local or Google File Search)', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_structural_grading',
            field=models.BooleanField(default=True, help_text='Use structural quality grading'),
        ),
    ]
