# Generated by Django 6.0.1 on 2026-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_storage_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='use_structural_grading',
        ),
        migrations.AddField(
            model_name='project',
            name='response_mode',
            field=models.CharField(choices=[('compact', 'Compact (Fastest - Stuffs Context into 1 Call)'), ('refine', 'Refine (Iterative - Thorough for Multi-Chunk Deep Analysis)'), ('tree_summarize', 'Tree Summarize (Hierarchical Summary for Broad Queries)')], default='compact', help_text="LlamaIndex response synthesis mode. 'Compact' maximizes speed and cuts LLM API calls.", max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='use_hyde',
            field=models.BooleanField(default=False, help_text='Enable Adaptive HyDE (Hypothetical Document Embeddings)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='document_parsing',
            field=models.CharField(choices=[('markitdown', 'markitdown')], default='markitdown', help_text='Document parsing backend (cannot be changed after first source is indexed).', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='embedding_model',
            field=models.CharField(choices=[('gemini-1', 'Gemini embedding 1')], default='gemini-1', help_text='Embedding model to use (cannot be changed after first source is indexed).', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_markitdown',
            field=models.BooleanField(default=False, help_text='Use MarkItDown pipeline (cannot be changed after first source is indexed).'),
        ),
    ]
