# Generated by Django 6.0.1 on 2026-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_use_structural_grading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='llm_model',
            field=models.CharField(choices=[('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (Cloud)'), ('gemma4:12b-mlx', 'Gemma 4 12B MLX (Local Ollama)')], default='gemini-2.5-flash-lite', help_text='LLM model used for synthesis, chat, and evaluation queries.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='embedding_model',
            field=models.CharField(choices=[('models/gemini-embedding-001', 'Gemini Embedding 001 (768-dim)'), ('gemini-1', 'Gemini embedding 1')], default='models/gemini-embedding-001', help_text='Embedding model to use (cannot be changed after first source is indexed).', max_length=100),
        ),
    ]
