# Generated by Django 6.0.1 on 2026-08-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_llm_model_alter_project_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='llm_model',
            field=models.CharField(choices=[('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (Cloud)'), ('gemma4:12b-mlx', 'Gemma 4 12B MLX (Local Ollama)'), ('gemma4:e2b-mlx', 'Gemma 4 E2B MLX (Local Ollama - Ultra Fast)'), ('gemma4:e4b-mlx', 'Gemma 4 E4B MLX (Local Ollama - Balanced)')], default='gemini-2.5-flash-lite', help_text='LLM model used for synthesis, chat, and evaluation queries.', max_length=100),
        ),
    ]
