# Generated by Django 6.0.1 on 2026-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disable_thinking',
            field=models.BooleanField(default=False, help_text='Disable reasoning/thinking mode for local Gemma models to accelerate response time.'),
        ),
    ]
