# Generated by Django 6.0.1 on 2026-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_llm_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='use_markitdown',
        ),
        migrations.AlterField(
            model_name='project',
            name='chunking',
            field=models.CharField(choices=[('gfs-default', 'Google File Search - Default'), ('fixed-size', 'Fixed-size'), ('sentence-paragraph', 'Sentence/paragraph'), ('recursive', 'Recursive'), ('document-structure', 'Document-structure'), ('semantic', 'Semantic')], default='fixed-size', help_text='Text chunking strategy', max_length=50),
        ),
    ]
