# Generated by Django 6.0.1 on 2026-08-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_project_use_markitdown_alter_project_chunking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='llm_model',
            field=models.CharField(default='gemini/gemini-2.5-flash-lite', help_text="LiteLLM model identifier used for synthesis, chat, and evaluation (e.g., 'gemini/gemini-2.5-flash', 'anthropic/claude-3-5-sonnet', 'openai/gpt-4o-mini', 'ollama/gemma4:12b-mlx').", max_length=255),
        ),
    ]
