# Generated by Django 6.0.1 on 2026-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='llm_model',
            field=models.CharField(default='gemini/gemini-2.5-flash-lite', help_text='LiteLLM model identifier used for synthesis, chat, and evaluation (e.g. <code>gemini/gemini-2.5-flash</code>, <code>anthropic/claude-3-5-sonnet</code>, <code>openai/gpt-4o-mini</code>, <code>ollama/gemma4:12b-mlx</code>). See <a href="https://models.litellm.ai/" target="_blank" style="color: #3b82f6; text-decoration: underline;">LiteLLM Model Directory</a>.', max_length=255, verbose_name='Model'),
        ),
    ]
