# Generated by Django 6.0.1 on 2026-08-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_llm_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chunking',
        ),
    ]
