# Generated by Django 6.0.1 on 2026-09-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_project_chunking'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_api_custom_prompt',
            field=models.BooleanField(default=False, help_text='Whether to allow the API to append additional instructions to the system prompt'),
        ),
    ]
