# Generated by Django 6.0.1 on 2026-01-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The API key (keep secret)', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Human-friendly name for this key', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('user', models.ForeignKey(help_text='The user this API key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='The API endpoint that was called', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP response status code')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(help_text='The API key that was used', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', '-created_at'], name='api_apiusag_api_key_0fd8c4_idx'), models.Index(fields=['-created_at'], name='api_apiusag_created_677328_idx')],
            },
        ),
    ]
