# Generated by Django 6.0.1 on 2026-08-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('projects', '0013_project_disable_thinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The specific project this API key is authorized for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.project'),
        ),
    ]
