# Generated by Django 6.0.1 on 2026-01-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(help_text='Name/path of the document', max_length=500)),
                ('display_name', models.CharField(blank=True, help_text='Human-friendly display name', max_length=500)),
                ('external_document_id', models.CharField(blank=True, help_text='ID from external service (e.g., Google Document ID)', max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, default='application/octet-stream', help_text='MIME type of the document', max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of the file in bytes', null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending Indexing'), ('INDEXING', 'Currently Indexing'), ('INDEXED', 'Successfully Indexed'), ('FAILED', 'Indexing Failed')], default='PENDING', help_text='Current indexing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, help_text='When the document was successfully indexed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if indexing failed')),
                ('project', models.ForeignKey(help_text='The project this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'state'], name='documents_d_project_5e312d_idx'), models.Index(fields=['state'], name='documents_d_state_df10a5_idx'), models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx')],
                'unique_together': {('project', 'document_name')},
            },
        ),
    ]
