# Generated by Django 6.0.1 on 2026-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='When this document expires', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_expired_checked',
            field=models.BooleanField(default=False, help_text='Whether this document has expiration tracking enabled'),
        ),
    ]
