# Generated by Django 6.0.1 on 2026-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_expiration_date_document_is_expired_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunking_strategy',
            field=models.CharField(choices=[('project_default', 'Use Project Default'), ('auto_detect', 'Auto-Detect by File Extension'), ('markdown', 'Markdown Header Splitter'), ('code', 'Code / AST Splitter'), ('hierarchical', 'Hierarchical / Parent-Child'), ('sentence', 'Sentence / Paragraph Splitter')], default='auto_detect', help_text='Document-specific chunking strategy.', max_length=50),
        ),
    ]
