# Generated by Django 6.0.1 on 2026-07-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_chunking_strategy'),
        ('projects', '0011_project_llm_model_alter_project_embedding_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsidianSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('obsidian', 'Obsidian')], default='document', help_text='Selected source type for this project (Document or Obsidian)', max_length=20)),
                ('vault_path', models.CharField(blank=True, help_text='Absolute local file directory path to the Obsidian vault', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When the vault was last synced', null=True)),
                ('project', models.OneToOneField(help_text='The project this Obsidian source is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='obsidian_source', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObsidianFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(help_text='Relative file path from vault root (e.g. Certifications/AWS_Guide.md)', max_length=1024)),
                ('folder_name', models.CharField(help_text='Immediate parent folder name (e.g. AWS)', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Indexing'), ('INDEXED', 'Successfully Indexed'), ('FAILED', 'Indexing Failed')], default='PENDING', help_text='Indexing status of this note', max_length=20)),
                ('file_mtime', models.FloatField(default=0.0, help_text='Last modified timestamp (mtime) of the note file')),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='When this note was last indexed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if note indexing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obsidian_source', models.ForeignKey(help_text='The Obsidian source this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.obsidiansource')),
            ],
            options={
                'ordering': ['relative_path'],
                'unique_together': {('obsidian_source', 'relative_path')},
            },
        ),
    ]
