# Generated by Django 6.0.1 on 2026-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_obsidiansource_obsidianfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsidianfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Indexing'), ('MODIFIED', 'Modified on Disk'), ('INDEXED', 'Successfully Indexed'), ('FAILED', 'Indexing Failed')], default='PENDING', help_text='Indexing status of this note', max_length=20),
        ),
    ]
