# Generated by Django 6.0.1 on 2026-08-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_obsidianfile_status'),
        ('projects', '0013_project_disable_thinking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsidiansource',
            name='source_type',
            field=models.CharField(choices=[('document', 'Document'), ('obsidian', 'Obsidian'), ('google_calendar', 'Google Calendar')], default='document', help_text='Selected source type for this project (Document, Obsidian, or Google Calendar)', max_length=20),
        ),
        migrations.CreateModel(
            name='GoogleCalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token')),
                ('token_expiry', models.DateTimeField(blank=True, help_text='OAuth access token expiration timestamp', null=True)),
                ('selected_calendars', models.JSONField(blank=True, default=list, help_text="List of calendar IDs to sync (e.g. ['primary', 'work_cal_id'])")),
                ('lookback_days', models.IntegerField(default=30, help_text='Lookback window in days (past events)')),
                ('lookahead_days', models.IntegerField(default=365, help_text='Lookahead window in days (future events)')),
                ('sync_token', models.CharField(blank=True, help_text='Google Calendar API syncToken for incremental delta sync', max_length=512)),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('SYNCING', 'Syncing Events'), ('INDEXING', 'Indexing Vectors'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', help_text='Current background synchronization status', max_length=20)),
                ('total_events_count', models.IntegerField(default=0)),
                ('indexed_events_count', models.IntegerField(default=0)),
                ('pending_events_count', models.IntegerField(default=0)),
                ('failed_events_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project this Google Calendar source is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_source', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Unique Google Calendar Event ID', max_length=255)),
                ('summary', models.CharField(help_text='Event summary / title', max_length=500)),
                ('relative_path', models.CharField(help_text='Relative file path of generated Markdown note (e.g. Calendar/2026-08-05_Sync.md)', max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Indexing'), ('INDEXED', 'Successfully Indexed'), ('FAILED', 'Indexing Failed')], default='PENDING', help_text='Indexing status of this calendar event', max_length=20)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('calendar_source', models.ForeignKey(help_text='The Google Calendar source this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.googlecalendarsource')),
            ],
            options={
                'ordering': ['-event_start'],
                'unique_together': {('calendar_source', 'event_id')},
            },
        ),
    ]
