# Generated by Django 6.0.1 on 2026-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_obsidiansource_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 cryptographic hash of binary for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stored key-value metadata tags'),
        ),
        migrations.AddField(
            model_name='document',
            name='store_file_id',
            field=models.CharField(blank=True, help_text='Google Document Resource Name (e.g., fileSearchStores/.../documents/...)', max_length=255),
        ),
    ]
