# Generated by Django 6.0.1 on 2026-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_content_hash_document_custom_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='chunking_strategy',
            field=models.CharField(choices=[('auto_detect', 'Auto-Detect by File Extension'), ('markdown', 'Markdown Header Splitter'), ('code', 'Code / AST Splitter'), ('hierarchical', 'Hierarchical / Parent-Child'), ('sentence', 'Sentence / Paragraph Splitter')], default='auto_detect', help_text='Document-specific chunking strategy.', max_length=50),
        ),
    ]
