# Generated by Django 6.0.1 on 2026-09-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_chunking_strategy'),
        ('projects', '0018_remove_project_chunking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.URLField(help_text='Entrypoint website URL', max_length=1024)),
                ('allowed_domain', models.CharField(help_text='Allowed domain/host (e.g. docs.example.com)', max_length=255)),
                ('subpath_only', models.BooleanField(default=True, help_text='Whether crawling is strictly constrained to the root URL subpath')),
                ('max_depth', models.PositiveIntegerField(default=4, help_text='Maximum link recursion depth')),
                ('max_pages', models.PositiveIntegerField(default=100, help_text='Maximum total pages to crawl')),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('DISCOVERING', 'Discovering Pages'), ('INDEXING', 'Indexing Vectors'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', help_text='Current background crawl/indexing status', max_length=20)),
                ('total_pages_count', models.IntegerField(default=0, help_text='Total discovered pages')),
                ('indexed_pages_count', models.IntegerField(default=0, help_text='Total successfully indexed pages')),
                ('pending_pages_count', models.IntegerField(default=0, help_text='Pages pending vector indexing')),
                ('failed_pages_count', models.IntegerField(default=0, help_text='Pages that failed crawling or indexing')),
                ('error_message', models.TextField(blank=True, help_text='Error message if crawl or indexing failed')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When the website source was last synced/crawled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project this website source belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='web_source', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='Normalized URL of the web page', max_length=2048)),
                ('title', models.CharField(blank=True, help_text='Extracted page title', max_length=500)),
                ('depth', models.PositiveIntegerField(default=0, help_text='Link depth relative to root URL')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Indexing'), ('INDEXING', 'Indexing Vectors'), ('INDEXED', 'Successfully Indexed'), ('MODIFIED', 'Modified on Remote Site'), ('FAILED', 'Failed'), ('DELETED', 'Deleted from Remote Site')], default='PENDING', help_text='Current indexing status of this page', max_length=20)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of extracted clean Markdown content', max_length=64)),
                ('etag', models.CharField(blank=True, help_text='HTTP ETag header for cache validation', max_length=255)),
                ('last_modified_header', models.CharField(blank=True, help_text='HTTP Last-Modified header value', max_length=255)),
                ('http_status', models.IntegerField(blank=True, help_text='Last recorded HTTP response status code', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scraping or indexing failed')),
                ('last_scraped_at', models.DateTimeField(blank=True, help_text='Timestamp of when page was last fetched', null=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='Timestamp of when page was last vector indexed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_source', models.ForeignKey(help_text='The WebSource this page belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.websource')),
            ],
            options={
                'ordering': ['url'],
                'unique_together': {('web_source', 'url')},
            },
        ),
    ]
