# Generated by Django 6.0.1 on 2026-01-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the evaluation dataset', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this dataset tests')),
                ('state', models.CharField(choices=[('PENDING', 'Pending Generation'), ('GENERATING', 'Currently Generating'), ('GENERATED', 'Successfully Generated'), ('FAILED', 'Generation Failed')], default='PENDING', help_text='Current generation status', max_length=20)),
                ('num_questions', models.IntegerField(default=10, help_text='Number of questions to generate')),
                ('question_generation_params', models.JSONField(blank=True, default=dict, help_text='Parameters used for question generation')),
                ('qa_pairs', models.JSONField(blank=True, default=list, help_text='Generated question-answer pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the dataset was generated', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('project', models.ForeignKey(help_text='The project this dataset is for', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_datasets', to='projects.project')),
                ('user', models.ForeignKey(blank=True, help_text='The user who created this dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(help_text='Name of the evaluator used', max_length=255)),
                ('metrics', models.JSONField(default=dict, help_text='Evaluation metrics (faithfulness, relevance, etc.)')),
                ('individual_scores', models.JSONField(blank=True, default=list, help_text='Per-question evaluation scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(help_text='The dataset this evaluation is for', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluate.evaluationdataset')),
                ('project', models.ForeignKey(help_text='The project being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluationdataset',
            index=models.Index(fields=['project', 'state'], name='evaluate_ev_project_de55b9_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationdataset',
            index=models.Index(fields=['state'], name='evaluate_ev_state_a3ff45_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['dataset', 'evaluator_name'], name='evaluate_ev_dataset_d1ca59_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['project'], name='evaluate_ev_project_4b6c04_idx'),
        ),
    ]
