# Generated by Django 6.0.1 on 2026-01-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'Assistant Response')], default='user', help_text='Type of message (user or assistant)', max_length=20)),
                ('content', models.TextField(help_text='The actual message content')),
                ('response_html', models.TextField(blank=True, help_text='HTML-formatted response (markdown rendered)')),
                ('context_documents', models.JSONField(blank=True, default=list, help_text='List of documents used as context for this response')),
                ('system_prompt_used', models.TextField(blank=True, help_text='The system prompt that was used for this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for grouping conversations', max_length=100)),
                ('project', models.ForeignKey(help_text='The project this chat is for', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='projects.project')),
                ('user', models.ForeignKey(blank=True, help_text='The user who sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='chat_chatme_project_b13469_idx'), models.Index(fields=['session_id', '-created_at'], name='chat_chatme_session_ff25f5_idx'), models.Index(fields=['message_type'], name='chat_chatme_message_1f44ae_idx')],
            },
        ),
    ]
