# Generated by Django 6.0.1 on 2026-08-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projects', '0013_project_disable_thinking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='The ID of the message being evaluated', max_length=255)),
                ('conversation_id', models.CharField(blank=True, db_index=True, help_text='Conversation or session identifier', max_length=255)),
                ('customer_id', models.CharField(blank=True, help_text='External customer identifier', max_length=255)),
                ('value', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], help_text="Feedback value ('up' or 'down')", max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, help_text='Timestamp sent from client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Server creation timestamp')),
                ('project', models.ForeignKey(help_text='The project this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='chat_chatfe_project_c8031f_idx'), models.Index(fields=['project', 'value'], name='chat_chatfe_project_8d2f43_idx'), models.Index(fields=['message_id'], name='chat_chatfe_message_ff1eee_idx')],
            },
        ),
    ]
