# Generated by Django 6.0.1 on 2026-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfeedback',
            name='query',
            field=models.TextField(blank=True, default='', help_text='The user question/query associated with this feedback'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='reply',
            field=models.TextField(blank=True, default='', help_text='The assistant reply associated with this feedback'),
        ),
    ]
