# Generated by Django 6.0.1 on 2026-08-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatfeedback_query_chatfeedback_reply'),
        ('projects', '0017_alter_project_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this chat is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='projects.project'),
        ),
    ]
