# Generated by Django 6.0.1 on 2026-06-02 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The reference question to search and evaluate')),
                ('ground_truth', models.TextField(help_text='The gold-standard ground-truth reference answer')),
                ('source', models.CharField(choices=[('GENERATED', 'Generated'), ('MANUAL', 'Manual'), ('CSV_UPLOAD', 'CSV Upload')], default='MANUAL', help_text='Source of the dataset pair acquisition', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, help_text='The document this QA pair was generated from (null for manual/CSV-uploaded QAs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_items', to='documents.document')),
                ('project', models.ForeignKey(help_text='The project this validation item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dataset_items', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Current state of the evaluation run', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is FAILED')),
                ('project', models.ForeignKey(help_text='The project being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResultMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_recall', models.FloatField(blank=True, help_text='Context Recall score', null=True)),
                ('context_precision', models.FloatField(blank=True, help_text='Context Precision score', null=True)),
                ('faithfulness', models.FloatField(blank=True, help_text='Faithfulness score', null=True)),
                ('answer_relevancy', models.FloatField(blank=True, help_text='Answer Relevancy score', null=True)),
                ('dataset_item', models.ForeignKey(help_text='The reference QA dataset item evaluated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_metrics', to='evaluate.evaluationdataset')),
                ('run', models.ForeignKey(help_text='The evaluation run this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='result_metrics', to='evaluate.evaluationrun')),
            ],
        ),
    ]
