# Generated by Django 6.0.1 on 2026-07-24 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
        ('projects', '0009_alter_project_storage_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('MANUAL_INPUT', 'Manual Input'), ('CSV_UPLOAD', 'CSV Upload')], default='MANUAL_INPUT', help_text='Origin of the question set', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='The project being evaluated manually', on_delete=django.db.models.deletion.CASCADE, related_name='manual_evaluation_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualEvaluationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The question to evaluate')),
                ('answer', models.TextField(blank=True, default='', help_text='Generated response from the project RAG API')),
                ('citations', models.JSONField(blank=True, default=list, help_text='List of context texts/sources retrieved for answer')),
                ('rating', models.CharField(choices=[('UNRATED', 'Unrated'), ('GREEN', 'Good'), ('ORANGE', 'Needs Improvement'), ('RED', 'Bad')], default='UNRATED', help_text='Human evaluator score rating', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='PENDING', help_text='Answer generation state', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if answer generation failed')),
                ('run', models.ForeignKey(help_text='The manual evaluation run this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluate.manualevaluationrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
