# Generated by Django 6.0.1 on 2026-08-17 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_manualevaluationrun_manualevaluationitem'),
        ('projects', '0013_project_disable_thinking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLLMEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('models_evaluated', models.JSONField(default=list, help_text='List of local Ollama model names evaluated in this run')),
                ('dataset_name', models.CharField(default='Custom Benchmark CSV', help_text='Name or source identifier of the benchmark dataset', max_length=255)),
                ('total_questions', models.IntegerField(default=0, help_text='Total number of evaluated question-answer pairs')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Current state of the local LLM benchmark run', max_length=20)),
                ('best_model', models.CharField(blank=True, default='', help_text='Model with the highest overall benchmark score', max_length=128)),
                ('best_overall_score', models.FloatField(blank=True, help_text='Highest overall score (out of 10) achieved across evaluated models', null=True)),
                ('summary_scores', models.JSONField(blank=True, default=dict, help_text='Aggregated per-model scorecard metrics breakdown')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if status is FAILED')),
                ('project', models.ForeignKey(help_text='The project being evaluated against local LLMs', on_delete=django.db.models.deletion.CASCADE, related_name='local_llm_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalLLMResultMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Name of the evaluated local Ollama model', max_length=128)),
                ('question', models.TextField(help_text='Evaluation query')),
                ('ground_truth', models.TextField(help_text='Reference gold-standard answer')),
                ('retrieved_context', models.TextField(blank=True, default='', help_text='Context chunks retrieved from the project for this query')),
                ('model_answer', models.TextField(blank=True, default='', help_text='Response text generated by the local LLM')),
                ('faithfulness', models.FloatField(default=0.0, help_text='Score out of 10: Grounding in retrieved context without hallucination')),
                ('context_utilization', models.FloatField(default=0.0, help_text='Score out of 10: Extraction of relevant facts from context')),
                ('citation_accuracy', models.FloatField(default=0.0, help_text='Score out of 10: Accurate citation of source notes and headings')),
                ('tokens_per_second', models.FloatField(default=0.0, help_text='Throughput speed in tokens per second')),
                ('reply_time', models.FloatField(default=0.0, help_text='Total query latency (Time to First Token + generation duration in seconds)')),
                ('instruction_following', models.FloatField(default=0.0, help_text='Score out of 10: Adherence to prompt format and instructions')),
                ('markdown_compatibility', models.FloatField(default=0.0, help_text='Score out of 10: Clean markdown formatting without syntax errors')),
                ('overall_score', models.FloatField(default=0.0, help_text='Exact arithmetic mean score out of 10 across all 7 criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(help_text='The benchmark run this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='item_metrics', to='evaluate.localllmevaluationrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
